### ISSUE TITLE
Buggy headers

### ISSUE THREAD

**Issue by ddobrev** [radiumone/r1-connect-demo-iOS#3]
Your headers are useless. To fix, add imports as follows:

R1EmitterLineItem.h - #import <Foundation/Foundation.h>
R1Push.h - #import <UIKit/UIKit.h>
R1SDK.h - #import <UIKit/UIKit.h>

**Comment by rajnigupta76** [comment]
My App is rejected for using non public method keyword in LibR1Connect.a
"Your app uses or references the following non-public APIs:

itemID, phone, granted, itemName, email, currency"

could you guys change above keyword with the differant name
