### ISSUE TITLE
iOS App Rejected For using Non Public API

### ISSUE THREAD

**Issue by rajnigupta76** [radiumone/r1-connect-demo-iOS#4]
My App is rejected for using non public method keyword in LibR1Connect.a
"Your app uses or references the following non-public APIs:

itemID, phone, granted, itemName, email, currency"

could you guys change above keyword with the differant names

**Comment by HenryMills** [comment]
We will take a look.  Hope to have a solution shortly.  Can you please send future requests to connectsupport@radiumone.com?
